# -*- coding: utf-8 -*-
"""All circulating world currencies (ISO 4217). code -> (name, symbol)."""

CURRENCIES = {
    "PKR": ("Pakistani Rupee", "Rs."),
    "USD": ("US Dollar", "$"),
    "EUR": ("Euro", "\u20ac"),
    "GBP": ("British Pound", "\u00a3"),
    "INR": ("Indian Rupee", "\u20b9"),
    "AED": ("UAE Dirham", "\u062f.\u0625"),
    "SAR": ("Saudi Riyal", "\ufdfc"),
    "AFN": ("Afghan Afghani", "\u060b"),
    "ALL": ("Albanian Lek", "L"),
    "AMD": ("Armenian Dram", "\u058f"),
    "ANG": ("Netherlands Antillean Guilder", "\u0192"),
    "AOA": ("Angolan Kwanza", "Kz"),
    "ARS": ("Argentine Peso", "$"),
    "AUD": ("Australian Dollar", "A$"),
    "AWG": ("Aruban Florin", "\u0192"),
    "AZN": ("Azerbaijani Manat", "\u20bc"),
    "BAM": ("Bosnia-Herzegovina Mark", "KM"),
    "BBD": ("Barbadian Dollar", "$"),
    "BDT": ("Bangladeshi Taka", "\u09f3"),
    "BGN": ("Bulgarian Lev", "\u043b\u0432"),
    "BHD": ("Bahraini Dinar", ".\u062f.\u0628"),
    "BIF": ("Burundian Franc", "FBu"),
    "BMD": ("Bermudan Dollar", "$"),
    "BND": ("Brunei Dollar", "$"),
    "BOB": ("Bolivian Boliviano", "Bs."),
    "BRL": ("Brazilian Real", "R$"),
    "BSD": ("Bahamian Dollar", "$"),
    "BTN": ("Bhutanese Ngultrum", "Nu."),
    "BWP": ("Botswanan Pula", "P"),
    "BYN": ("Belarusian Ruble", "Br"),
    "BZD": ("Belize Dollar", "BZ$"),
    "CAD": ("Canadian Dollar", "C$"),
    "CDF": ("Congolese Franc", "FC"),
    "CHF": ("Swiss Franc", "CHF"),
    "CLP": ("Chilean Peso", "$"),
    "CNY": ("Chinese Yuan", "\u00a5"),
    "COP": ("Colombian Peso", "$"),
    "CRC": ("Costa Rican Colon", "\u20a1"),
    "CUP": ("Cuban Peso", "$"),
    "CVE": ("Cape Verdean Escudo", "$"),
    "CZK": ("Czech Koruna", "K\u010d"),
    "DJF": ("Djiboutian Franc", "Fdj"),
    "DKK": ("Danish Krone", "kr"),
    "DOP": ("Dominican Peso", "RD$"),
    "DZD": ("Algerian Dinar", "\u062f.\u062c"),
    "EGP": ("Egyptian Pound", "\u00a3"),
    "ERN": ("Eritrean Nakfa", "Nfk"),
    "ETB": ("Ethiopian Birr", "Br"),
    "FJD": ("Fijian Dollar", "$"),
    "FKP": ("Falkland Islands Pound", "\u00a3"),
    "GEL": ("Georgian Lari", "\u20be"),
    "GHS": ("Ghanaian Cedi", "\u20b5"),
    "GIP": ("Gibraltar Pound", "\u00a3"),
    "GMD": ("Gambian Dalasi", "D"),
    "GNF": ("Guinean Franc", "FG"),
    "GTQ": ("Guatemalan Quetzal", "Q"),
    "GYD": ("Guyanaese Dollar", "$"),
    "HKD": ("Hong Kong Dollar", "HK$"),
    "HNL": ("Honduran Lempira", "L"),
    "HRK": ("Croatian Kuna", "kn"),
    "HTG": ("Haitian Gourde", "G"),
    "HUF": ("Hungarian Forint", "Ft"),
    "IDR": ("Indonesian Rupiah", "Rp"),
    "ILS": ("Israeli Shekel", "\u20aa"),
    "IQD": ("Iraqi Dinar", "\u0639.\u062f"),
    "IRR": ("Iranian Rial", "\ufdfc"),
    "ISK": ("Icelandic Krona", "kr"),
    "JMD": ("Jamaican Dollar", "J$"),
    "JOD": ("Jordanian Dinar", "\u062f.\u0627"),
    "JPY": ("Japanese Yen", "\u00a5"),
    "KES": ("Kenyan Shilling", "KSh"),
    "KGS": ("Kyrgystani Som", "\u043b\u0432"),
    "KHR": ("Cambodian Riel", "\u17db"),
    "KMF": ("Comorian Franc", "CF"),
    "KPW": ("North Korean Won", "\u20a9"),
    "KRW": ("South Korean Won", "\u20a9"),
    "KWD": ("Kuwaiti Dinar", "\u062f.\u0643"),
    "KYD": ("Cayman Islands Dollar", "$"),
    "KZT": ("Kazakhstani Tenge", "\u20b8"),
    "LAK": ("Laotian Kip", "\u20ad"),
    "LBP": ("Lebanese Pound", "\u00a3"),
    "LKR": ("Sri Lankan Rupee", "Rs"),
    "LRD": ("Liberian Dollar", "$"),
    "LSL": ("Lesotho Loti", "L"),
    "LYD": ("Libyan Dinar", "\u0644.\u062f"),
    "MAD": ("Moroccan Dirham", "\u062f.\u0645."),
    "MDL": ("Moldovan Leu", "L"),
    "MGA": ("Malagasy Ariary", "Ar"),
    "MKD": ("Macedonian Denar", "\u0434\u0435\u043d"),
    "MMK": ("Myanmar Kyat", "K"),
    "MNT": ("Mongolian Tugrik", "\u20ae"),
    "MOP": ("Macanese Pataca", "MOP$"),
    "MRU": ("Mauritanian Ouguiya", "UM"),
    "MUR": ("Mauritian Rupee", "\u20a8"),
    "MVR": ("Maldivian Rufiyaa", "Rf"),
    "MWK": ("Malawian Kwacha", "MK"),
    "MXN": ("Mexican Peso", "$"),
    "MYR": ("Malaysian Ringgit", "RM"),
    "MZN": ("Mozambican Metical", "MT"),
    "NAD": ("Namibian Dollar", "$"),
    "NGN": ("Nigerian Naira", "\u20a6"),
    "NIO": ("Nicaraguan Cordoba", "C$"),
    "NOK": ("Norwegian Krone", "kr"),
    "NPR": ("Nepalese Rupee", "\u20a8"),
    "NZD": ("New Zealand Dollar", "NZ$"),
    "OMR": ("Omani Rial", "\ufdfc"),
    "PAB": ("Panamanian Balboa", "B/."),
    "PEN": ("Peruvian Sol", "S/."),
    "PGK": ("Papua New Guinean Kina", "K"),
    "PHP": ("Philippine Peso", "\u20b1"),
    "PLN": ("Polish Zloty", "z\u0142"),
    "PYG": ("Paraguayan Guarani", "\u20b2"),
    "QAR": ("Qatari Rial", "\ufdfc"),
    "RON": ("Romanian Leu", "lei"),
    "RSD": ("Serbian Dinar", "\u0434\u0438\u043d."),
    "RUB": ("Russian Ruble", "\u20bd"),
    "RWF": ("Rwandan Franc", "FRw"),
    "SBD": ("Solomon Islands Dollar", "$"),
    "SCR": ("Seychellois Rupee", "\u20a8"),
    "SDG": ("Sudanese Pound", "\u062c.\u0633."),
    "SEK": ("Swedish Krona", "kr"),
    "SGD": ("Singapore Dollar", "S$"),
    "SHP": ("St. Helena Pound", "\u00a3"),
    "SLL": ("Sierra Leonean Leone", "Le"),
    "SOS": ("Somali Shilling", "Sh"),
    "SRD": ("Surinamese Dollar", "$"),
    "SSP": ("South Sudanese Pound", "\u00a3"),
    "STN": ("Sao Tome Dobra", "Db"),
    "SYP": ("Syrian Pound", "\u00a3"),
    "SZL": ("Swazi Lilangeni", "L"),
    "THB": ("Thai Baht", "\u0e3f"),
    "TJS": ("Tajikistani Somoni", "SM"),
    "TMT": ("Turkmenistani Manat", "m"),
    "TND": ("Tunisian Dinar", "\u062f.\u062a"),
    "TOP": ("Tongan Pa'anga", "T$"),
    "TRY": ("Turkish Lira", "\u20ba"),
    "TTD": ("Trinidad & Tobago Dollar", "TT$"),
    "TWD": ("New Taiwan Dollar", "NT$"),
    "TZS": ("Tanzanian Shilling", "TSh"),
    "UAH": ("Ukrainian Hryvnia", "\u20b4"),
    "UGX": ("Ugandan Shilling", "USh"),
    "UYU": ("Uruguayan Peso", "$U"),
    "UZS": ("Uzbekistani Som", "\u043b\u0432"),
    "VES": ("Venezuelan Bolivar", "Bs."),
    "VND": ("Vietnamese Dong", "\u20ab"),
    "VUV": ("Vanuatu Vatu", "VT"),
    "WST": ("Samoan Tala", "WS$"),
    "XAF": ("Central African CFA Franc", "FCFA"),
    "XCD": ("East Caribbean Dollar", "$"),
    "XOF": ("West African CFA Franc", "CFA"),
    "XPF": ("CFP Franc", "\u20a3"),
    "YER": ("Yemeni Rial", "\ufdfc"),
    "ZAR": ("South African Rand", "R"),
    "ZMW": ("Zambian Kwacha", "ZK"),
    "ZWL": ("Zimbabwean Dollar", "Z$"),
}

# Sorted choices: common ones first, then alphabetical
_PRIORITY = ["PKR", "USD", "EUR", "GBP", "INR", "AED", "SAR"]
def currency_choices():
    out = []
    for code in _PRIORITY:
        name, sym = CURRENCIES[code]
        out.append((code, f"{code} - {name} ({sym})"))
    for code in sorted(CURRENCIES):
        if code in _PRIORITY:
            continue
        name, sym = CURRENCIES[code]
        out.append((code, f"{code} - {name} ({sym})"))
    return out

CURRENCY_CHOICES = currency_choices()

def symbol_for(code):
    return CURRENCIES.get(code, ("", "Rs."))[1]
