# Generated by Django 6.0.6 on 2026-06-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='theme',
            field=models.CharField(choices=[('light', 'Light (Classic Orange)'), ('sage', 'Sage Green'), ('olive', 'Olive Green'), ('ocean', 'Ocean Blue'), ('charcoal', 'Charcoal (Dark)')], default='light', max_length=12),
        ),
        migrations.AddField(
            model_name='lockerassignment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Locker fee actually paid. Locker is assigned only when this covers the rate.', max_digits=8),
        ),
    ]
