# Generated by Django 6.0.6 on 2026-06-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gym_theme_lockerassignment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='currency_code',
            field=models.CharField(default='PKR', max_length=4),
        ),
        migrations.AddField(
            model_name='gym',
            name='owner_key',
            field=models.CharField(default='0000', help_text='4-digit PIN required to switch into Owner mode', max_length=4),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly subscription fee charged to this gym', max_digits=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_until',
            field=models.DateField(blank=True, help_text='Access is blocked after this date until renewed', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='left_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='left_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='currency',
            field=models.CharField(default='Rs.', max_length=8),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('pending', 'Pending Approval'), ('freeze', 'Membership Frozen'), ('left', 'Left / Former Member')], default='active', max_length=10),
        ),
    ]
